### ISSUE TITLE
2 people, 1 CG issue

### ISSUE THREAD

**Issue by Velikiy-Knyaz** [ScootsChan/rKanColleLounge#2]
I notice that Scoots is using our flairs to represent us, but what happens when two people using the same flair have to talk to each other for story reasons and/or have to talk to the same ship girl who's image they're using? We could end up with a lot of headaches really fast.

**Comment by ScootsChan** [comment]
Currently, I was planning on using the flair ships as a placeholder until we get an artist on board to design actual admirals. In order to prevent confusion in the early stages when we are using the placeholders, we could try slapping on random objects relevant to the admiral in question. 

Here are two examples of my concept (me w/ us army shit and astraph with a ushanka & polish flags):

![scoots concept](https://user-images.githubusercontent.com/28407756/33227917-5348fa3c-d17c-11e7-9fb4-82e29111ec34.png)
![astraph concept](https://user-images.githubusercontent.com/28407756/33227918-5353e55a-d17c-11e7-86ef-4ad5a03e9286.png)

**Comment by ScootsChan** [comment]
Fixed problem by using the hat idea, see commit labelled "d9f3591452c262eddce20bd40bf3710baaa60a43".
